### ISSUE TITLE
Configuration for setting 3rd mybinder services

### ISSUE THREAD

**Issue by seisman** [s-weigand/trigger-mybinder-build#6]
**Is your feature request related to a problem? Please describe.**

Currently, this github action triggers build on following mybinder sites:

https://github.com/s-weigand/trigger-mybinder-build/blob/e874709719275d05418fc159888092435447d1af/src/request_trigger.ts#L68-L74

Sometimes, I find that mybinder.org is slow, and prefer to use https://binder.pangeo.io/, a mybinder service provided by [Pangeo](https://pangeo.io/), a community platform for Big Data geoscience. However, this github action can't trigger the pangeo binder.

**Describe the solution you'd like**

Could you please add a configuration setting to allow users add other binder sites?

**Comment by s-weigand** [comment]
v1.0.2 (new v1) adds this feature.

To request a build on Pangeo, just add the following line to your configuration.
```yaml
          additional-build-servers: |
             https://binder.pangeo.io
```
If you only want to build Pangeo and skip the default binder servers you can also do that.

```yaml
          use-default-build-servers: false
```

**Comment by seisman** [comment]
Great! Thanks.
